on:
  # The event respository_dispatch means on every API trigger,
  # this whole file gets executed
  repository_dispatch:
    types: [deploy-service]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: Tony1106/workflow@test
        with:
          who-to-greet: "Mona the Tony"
      # Use the output from the `hello` step
      - uses: actions/checkout@v3
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: |
          echo "$GITHUB_CONTEXT"
          touch hello.md
          git config --global user.name "tony bui"
          git config --global user.email "buiminhtien06@gmail.com"
          git add .
          git commit -m "generated"
          git push
